=== DAM1-COTARELO-25-26/proyecto-web-breixo-y-sonia/xml/tablaDes.dtd
<!ELEMENT tablaDestinos (destino+)>
<!ELEMENT destino (ciudad, pais, duracion, coste)>
<!ATTLIST destino id CDATA #REQUIRED>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT coste (#PCDATA)>

=== DAM1-COTARELO-25-26/proyecto-web-breixo-y-sonia/datos/tablaDestinos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tablaDestinos SYSTEM "tablaDes.dtd">
<tablaDestinos>
    <destino id="1">
        <ciudad>Roma</ciudad>
        <pais>Italia</pais>
        <duracion>7 dias</duracion>
        <coste>890€</coste>
    </destino>
    <destino id="2">
        <ciudad>Paris</ciudad>
        <pais>Francia</pais>
        <duracion>5 dias</duracion>
        <coste>750€</coste>
    </destino>
    <destino id="3">
        <ciudad>Praga</ciudad>
        <pais>Republica Checa</pais>
        <duracion>6 dias</duracion>
        <coste>820€</coste>
    </destino>
</tablaDestinos>
